version: "3"

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data_container:/data/redis

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        volumes:
            - postgres_data_container:/data/postgresql
        ports:
            - "5432:5432"

volumes:
    redis_data_container:
        driver: local
    postgres_data_container:
        driver: local
